### ISSUE TITLE
Add support to modify data read from the uploaded file

### ISSUE THREAD

**Issue by jienius** [eddieantonio/predictive-text-studio#38]
i.e overwrite count for some words, delete or add new word counts

Specific Requirements: 

* Users can click on the 'edit' icon for any source (Excel, Google Sheet, Manual Entry) to display a table with current values from storage

* Each word will have a row where the word and the count are visible in input text boxes.

* Users can edit values by selecting a text box and tying in a value to update.

  * Values for words cannot be empty and  have to be strings

  * Values for word counts have to be > 0 or empty

  * When users click on an input field, the row should change to match the style for selected input fields.

* Users can click on an 'X' arrow to delete a word from storage.

* There will be a 'new row' at the top of the table where users can type in a new word.

  * When users enter in a value for the row, another new row should appear on top (i.e. there is no 'add word' button and this is done automatically)

* The table name can be edited via a text box.

* The table automatically saves periodically or can be manually saved.

* The table can be closed via a 'close' button

**Comment by yehee** [comment]
Seems like it overlaps with #257. I've come up with a list of features still to be worked on:

- ~Users can click on the 'edit' icon for any source (Excel, Google Sheet, Manual Entry) to display a table with current values from storage~
- ~Each word will have a row where the word and the count are visible in input text boxes.~
- ~Users can edit values by selecting a text box and trying in a value to update.~
- ~Values for words cannot be empty and have to be strings.~ **_(although I'm not sure whether "8" be counted as a string)_**
- ~Values for word counts have to be > 0 or empty.~
- **_When users click on an input field, the row should change to match the style for selected input fields._**
- ~Users can click on an 'X' arrow to delete a word from storage.~
- ~There will be a 'new row' at the top of the table where users can type in a new word.~
- **_When users enter in a value for the row, another new row should appear on top (i.e. there is no 'add word' button and this is done automatically)_**
- **_The table name can be edited via a text box._**
- ~The table automatically saves periodically or can be manually saved.~
- ~**_The table can be closed via a 'close' button._**~

**Comment by yehee** [comment]
@eddieantonio Could I ask for clarification for the below points:
- Values for words cannot be empty and have to be strings: should we check to make sure if it doesn't contain only the numbers, e.g. "8"?
- When users click on an input field, the row should change to match the style for selected input fields.
- When users enter in a value for the row, another new row should appear on top (i.e. there is no 'add word' button and this is done automatically)

Thank you so much!

**Comment by eddieantonio** [comment]
> @eddieantonio Could I ask for clarification for the below points:
> 
> * Values for words cannot be empty and have to be strings: should we check to make sure if it doesn't contain only the numbers, e.g. "8"?

Words should not be _empty_, but it's totally fine for the wordlist to contain digits, punctuation, symbols, etc. To define what "empty" means:

The field is empty when:
 - after removing all code points from the string belonging to [Unicode General Category=Z](https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)#cite_ref-fn3_3-0:~:text=Z%2C%20Separator);
 - the resultant string has 0 code points

Characters of all other categories are fine, except for [Unicode General Category=Cs](https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)#cite_ref-fn4_4-0:~:text=characters-,Cs), unpaired surrogate code points, which must NEVER appear in any well-formed string. (hint: you should NOT have to deal with unmatched surrogate pairs!)

> * When users click on an input field, the row should change to match the style for selected input fields.

There should be a highlight or outline when you click on the input field, like most input fields on the web. This is for usability and accessibility.

> * When users enter in a value for the row, another new row should appear on top (i.e. there is no 'add word' button and this is done automatically)

When you start typing in the latest row, and new row should be **automatically** created, so that you can enter the next word
